project:
  type: website
  output-dir: docs

website:
  title: "Emma's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu:
        - datavizone.qmd
        - dataviztwo.qmd
        - text: Shiny App
          href: https://em4567.shinyapps.io/shiny_app/ 
      - href: textanalysis.qmd
        text: Text Analysis
      - href: PermutationTest.qmd
        text: Permutation Test
      - href: Ethics.qmd
        text: Ethics
      - href: SQL.qmd
        text: SQL
      - href: FinalPresentation.qmd
        text: Final Presentation

format:
  html:
    theme: 
      light: morph
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

